### PR TITLE
Npm Updates

### PR DESCRIPTION
**Pull request by dargmuesli**
See [gulp-phplint/#42](https://github.com/mikeerickson/gulp-phplint/issues/42).

Created individual commits so you can see the changes that each NPM command generates individually. Squashable of course.

### CODE REVIEW

**Comment by Dargmuesli** [comment]
I've also created an issue at [danielb2/purdy.js](https://github.com/danielb2/purdy.js/issues/63) to get the remaining 3 vulnerabilities fixed.

**Comment by mikeerickson** [comment]
@Dargmuesli Ya, it is quite the rabbit hole sometimes.  I am actually thinking to instead remove gulp-messenger all together and just fall back to simple console logs

**Comment by Dargmuesli** [comment]
Sounds good to me :D

**Comment by mikeerickson** [comment]
@Dargmuesli OK, I think it is all clean now, could you please have a quick look.  I dont have my complete test setup here (I am at work and dont have a test PHP project to work against)

I have removed gulp-messenger

```
https://www.npmjs.com/package/gulp-phplint
```

Tagged version: 0.7.1

**Comment by Dargmuesli** [comment]
Looks pretty good so far!

**Pull request closed without merging**
